# Generated by Django 4.2 on 2023-05-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneXcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, verbose_name='phone_number')),
                ('xcode', models.CharField(max_length=10, verbose_name='xcode')),
            ],
            options={
                'verbose_name': 'Код подверждения',
            },
        ),
    ]
