# Generated by Django 4.2.1 on 2023-05-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Абонимент", "verbose_name_plural": "Абонименты"},
        ),
    ]
