# Generated by Django 4.2 on 2023-05-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_phonexcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(default='12.12.2000', verbose_name='День рождения'),
        ),
    ]
